apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts

helmCharts:
- name: istio-base
  includeCRDs: true
  releaseName: istio-base
  namespace: istio-system
  repo: istio-base
