apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istiod
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          infra.istio: "enabled"
  template:
    metadata:
      name: istiod
    spec:
      project: default
      source:
        repoURL: https://github.com/1602077/gitops-argo.git
        targetRevision: HEAD
        path: services/istiod/base
      destination:
        server: https://kubernetes.default.svc
        namespace: istio-system
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
