apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core
  namespace: core
spec:
  description: core infra
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
