apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argo
  namespace: argocd
spec:
  hosts:
  - "*"
  gateways:
  - public-gateway
  - public-gateway.istio-ingress.svc.cluster.local
  # - mesh
  # - istio-ingress/public-gateway
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: argocd-server
        port:
          number: 80
