# Deploys crossplane to clusters that have the `infra.crossplane: "enabled"`
# label. There should currently be only one cluster running crossplane in this
# multi-cluster setup.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: crossplane
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          infra.crossplane: "enabled"
  template:
    metadata:
      name: crossplane
    spec:
      project: default
      source:
        repoURL: https://github.com/1602077/cluster-config.git
        targetRevision: HEAD
        path: services/crossplane/base
      destination:
        server: https://kubernetes.default.svc
        namespace: crossplane-system
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true

