apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: crossplane
    includeCRDS: true
    releaseName: crossplane
    namespace: crossplane-system
    repo: crossplane
